# Generated by Django 6.0.1 on 2026-03-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_name',
            new_name='company',
        ),
    ]
